version: 2.1

branch_filters: &branch_filters
  filters:
    branches:
      only:
        - master

jobs:
  debug:
    machine:
      image: ubuntu-1604:201903-01
#     docker:
#       - image: circleci/python
    environment:
      CC: gcc-6
      CXX: g++-6
      CCACHE: /usr/bin/ccache
      RUSTFLAGS: -Dwarnings
      CARGO_INCREMENTAL: 0
    steps:
#         - checkout
        - run:
            name: script
            command: |              
              python --version
              pip --version
              ps              
              
              ls -a /opt/circleci/.pyenv/versions/3.5.2/bin/python3

              echo "Aee"
              alias python3=/opt/circleci/.pyenv/versions/3.5.2/bin/python3
              shopt -s expand_aliases
              echo "Bee"
              python3
              echo "Cee"
  
  no_env:
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - checkout
      - run:
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
            sudo apt install python-pip
            pip install virtualenv
            source ~/.profile
            export TERM=xterm
            ./mach test-tidy --no-progress --all
            ./mach test-tidy --no-progress --self-test
            python ./etc/memory_reports_over_time.py --test
            bash etc/ci/check_no_panic.sh

  env:
    machine:
      image: ubuntu-1604:201903-01
#     docker:
#       - image: circleci/python
    environment:
      CC: gcc-6
      CXX: g++-6
      CCACHE: /usr/bin/ccache
      RUSTFLAGS: -Dwarnings
      CARGO_INCREMENTAL: 0
    steps:
        - checkout
        - run:
            name: script
            command: |              
              python --version
              pip --version              
              
              sudo apt-get install software-properties-common
              sudo apt-get update
              sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
              sudo add-apt-repository 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.9 main' -y
              sudo apt-get update -q
              
              sudo apt-get install autoconf2.13 cmake g++-6 gperf libosmesa6-dev libgles2-mesa-dev python-virtualenv xorg-dev ccache libdbus-glib-1-dev libedit-dev libglib2.0-dev -y
              sudo apt-get install clang-3.9 llvm-3.9 llvm-3.9-runtime libunwind-dev -y
              curl -L https://servo-deps.s3.amazonaws.com/gstreamer/gstreamer-x86_64-linux-gnu.tar.gz | tar xz
              sed -i "s;prefix=/root/gstreamer;prefix=$PWD/gstreamer;g" $PWD/gstreamer/lib/x86_64-linux-gnu/pkgconfig/*.pc
              
              export PKG_CONFIG_PATH=$PWD/gst/lib/pkgconfig
              export GST_PLUGIN_SYSTEM_PATH=$PWD/gst/lib/gstreamer-1.0
              export GST_PLUGIN_SCANNER=$PWD/gst/libexec/gstreamer-1.0/gst-plugin-scanner
              export PATH=$PATH:$PWD/gst/bin
              export LD_LIBRARY_PATH=$PWD/gst/lib:$LD_LIBRARY_PATH
              export LLVM_CONFIG=llvm-config-3.9
              
              curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
              source ~/.profile
              export $TERM=xterm
              #export RUST_BACKTRACE=1
              ./mach bootstrap-gstreamer
              echo "Aee"              
              alias python3=/opt/circleci/.pyenv/versions/3.5.2/bin/python3 >> $BASH_ENV
              python3
              ./mach build -d --verbose -p servo
              echo "Beee"
              ./mach test-unit
              echo "Ceeee"
              ./mach clean
              echo "Deeeee"
              bash etc/ci/lockfile_changed.sh

workflows:
    version: 2    
    build:
      jobs:
      - debug
#       - no_env:
#           <<: *branch_filters
#       - env:
#           <<: *branch_filters
